// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module("SimpleTimeTrackPopup", ["ngRoute"]);


  /*
    Configure app
   */

  app.config([
    "$httpProvider", "$routeProvider", function($httpProvider, $routeProvider) {
      $httpProvider.interceptors.push("HttpErrorInterceptorModule");
      return $routeProvider.when("/overview", {
        templateUrl: "partials/popup.html",
        controller: "PopupController"
      }).when("/login", {
        templateUrl: "partials/login.html",
        controller: "LoginController"
      }).otherwise({
        redirectTo: "/overview"
      });
    }
  ]);


  /*
    Add current controller to $rootScope
   */

  app.run(function($rootScope) {
    return $rootScope.$on("$routeChangeSuccess", function(ev, data) {
      if (data.$$route && data.$$route.controller) {
        return $rootScope.controller = data.$$route.controller;
      }
    });
  });

}).call(this);
